// Auto-generated by refresh.py — do not edit by hand.
window.DASHBOARD_DATA = {
  "last_updated": "02 Sep 2026, 11:18 PM IST",
  "window_start": "09 Jul",
  "window_end": "02 Sep 2026",
  "live": 425,
  "engagement": {
    "clicked": 418,
    "clicks": 35275,
    "ct_profiles": 1131,
    "c1": 11,
    "c2": 15,
    "c3": 13,
    "c4plus": 379
  },
  "segments": {
    "clicked": {
      "base": 418,
      "active": 410,
      "slot": 410,
      "tech": 392,
      "install": 349,
      "tasks": 18956,
      "t_slot_prop": 15140,
      "t_slot_conf": 14246,
      "t_tech": 6600,
      "t_arrived": 3658,
      "t_install": 3523
    },
    "noclick": {
      "base": 7,
      "active": 7,
      "slot": 7,
      "tech": 6,
      "install": 1,
      "tasks": 402,
      "t_slot_prop": 268,
      "t_slot_conf": 259,
      "t_tech": 29,
      "t_arrived": 7,
      "t_install": 6
    },
    "nonmbg": {
      "base": 581,
      "active": 581,
      "slot": 555,
      "tech": 356,
      "install": 224,
      "tasks": 15023,
      "t_slot_prop": 11037,
      "t_slot_conf": 10644,
      "t_tech": 3961,
      "t_arrived": 1735,
      "t_install": 1583
    }
  },
  "enrolled_roster": {
    "total": 429,
    "with_leads": 421,
    "eff_60_plus": 64,
    "eff_60_minus": 357,
    "pending_only": 0,
    "no_activity": 8,
    "installs": 3877,
    "leads": 12103
  },
  "efficiency": {
    "june": {
      "enrolled": {
        "partners": 288,
        "leads": 854,
        "installs": 371,
        "agg_eff": 43.4,
        "secured": 95,
        "pct_secured": 33.0
      },
      "eligible": {
        "partners": 50,
        "leads": 96,
        "installs": 18,
        "agg_eff": 18.8,
        "secured": 4,
        "pct_secured": 8.0
      },
      "nonmbg": {
        "partners": 125,
        "leads": 362,
        "installs": 149,
        "agg_eff": 41.2,
        "secured": 38,
        "pct_secured": 30.4
      }
    },
    "july": {
      "enrolled": {
        "partners": 421,
        "leads": 12103,
        "installs": 3877,
        "agg_eff": 32.0,
        "secured": 64,
        "pct_secured": 15.2
      },
      "eligible": {
        "partners": 135,
        "leads": 3051,
        "installs": 535,
        "agg_eff": 17.5,
        "secured": 6,
        "pct_secured": 4.4
      },
      "nonmbg": {
        "partners": 416,
        "leads": 5055,
        "installs": 1099,
        "agg_eff": 21.7,
        "secured": 55,
        "pct_secured": 13.2
      }
    }
  }
};
