// Auto-generated by refresh.py — do not edit by hand.
window.DASHBOARD_DATA = {
  "last_updated": "16 Jul 2026, 09:52 PM IST",
  "window_start": "09 Jul",
  "window_end": "16 Jul 2026",
  "live": 425,
  "engagement": {
    "clicked": 340,
    "clicks": 3042,
    "ct_profiles": 476,
    "c1": 66,
    "c2": 49,
    "c3": 40,
    "c4plus": 185
  },
  "segments": {
    "clicked": {
      "base": 340,
      "active": 309,
      "slot": 220,
      "tech": 203,
      "install": 141,
      "tasks": 2714,
      "t_slot_prop": 1154,
      "t_slot_conf": 686,
      "t_tech": 577,
      "t_arrived": 286,
      "t_install": 262
    },
    "noclick": {
      "base": 85,
      "active": 80,
      "slot": 41,
      "tech": 29,
      "install": 12,
      "tasks": 675,
      "t_slot_prop": 147,
      "t_slot_conf": 80,
      "t_tech": 55,
      "t_arrived": 20,
      "t_install": 18
    },
    "nonmbg": {
      "base": 407,
      "active": 407,
      "slot": 160,
      "tech": 123,
      "install": 61,
      "tasks": 2738,
      "t_slot_prop": 666,
      "t_slot_conf": 417,
      "t_tech": 313,
      "t_arrived": 126,
      "t_install": 105
    }
  },
  "enrolled_roster": {
    "total": 429,
    "with_leads": 303,
    "eff_60_plus": 83,
    "eff_60_minus": 220,
    "pending_only": 24,
    "no_activity": 102,
    "installs": 584,
    "leads": 1312
  },
  "efficiency": {
    "june": {
      "enrolled": {
        "partners": 291,
        "leads": 874,
        "installs": 371,
        "agg_eff": 42.4,
        "secured": 92,
        "pct_secured": 31.6
      },
      "eligible": {
        "partners": 51,
        "leads": 100,
        "installs": 18,
        "agg_eff": 18.0,
        "secured": 4,
        "pct_secured": 7.8
      },
      "nonmbg": {
        "partners": 125,
        "leads": 368,
        "installs": 149,
        "agg_eff": 40.5,
        "secured": 37,
        "pct_secured": 29.6
      }
    },
    "july": {
      "enrolled": {
        "partners": 303,
        "leads": 1312,
        "installs": 584,
        "agg_eff": 44.5,
        "secured": 83,
        "pct_secured": 27.4
      },
      "eligible": {
        "partners": 56,
        "leads": 150,
        "installs": 45,
        "agg_eff": 30.0,
        "secured": 14,
        "pct_secured": 25.0
      },
      "nonmbg": {
        "partners": 157,
        "leads": 508,
        "installs": 154,
        "agg_eff": 30.3,
        "secured": 37,
        "pct_secured": 23.6
      }
    }
  }
};
