// Auto-generated by refresh.py — do not edit by hand.
window.DASHBOARD_DATA = {
  "last_updated": "21 Jul 2026, 05:56 PM IST",
  "window_start": "09 Jul",
  "window_end": "21 Jul 2026",
  "live": 425,
  "engagement": {
    "clicked": 369,
    "clicks": 5014,
    "ct_profiles": 583,
    "c1": 49,
    "c2": 41,
    "c3": 32,
    "c4plus": 247
  },
  "segments": {
    "clicked": {
      "base": 369,
      "active": 352,
      "slot": 272,
      "tech": 249,
      "install": 188,
      "tasks": 4543,
      "t_slot_prop": 1949,
      "t_slot_conf": 1178,
      "t_tech": 1001,
      "t_arrived": 508,
      "t_install": 468
    },
    "noclick": {
      "base": 56,
      "active": 53,
      "slot": 31,
      "tech": 24,
      "install": 9,
      "tasks": 704,
      "t_slot_prop": 130,
      "t_slot_conf": 77,
      "t_tech": 52,
      "t_arrived": 19,
      "t_install": 18
    },
    "nonmbg": {
      "base": 449,
      "active": 449,
      "slot": 204,
      "tech": 163,
      "install": 87,
      "tasks": 4150,
      "t_slot_prop": 1038,
      "t_slot_conf": 679,
      "t_tech": 521,
      "t_arrived": 222,
      "t_install": 182
    }
  },
  "enrolled_roster": {
    "total": 429,
    "with_leads": 330,
    "eff_60_plus": 96,
    "eff_60_minus": 234,
    "pending_only": 22,
    "no_activity": 77,
    "installs": 800,
    "leads": 1736
  },
  "efficiency": {
    "june": {
      "enrolled": {
        "partners": 288,
        "leads": 854,
        "installs": 371,
        "agg_eff": 43.4,
        "secured": 95,
        "pct_secured": 33.0
      },
      "eligible": {
        "partners": 50,
        "leads": 96,
        "installs": 18,
        "agg_eff": 18.8,
        "secured": 4,
        "pct_secured": 8.0
      },
      "nonmbg": {
        "partners": 125,
        "leads": 362,
        "installs": 149,
        "agg_eff": 41.2,
        "secured": 38,
        "pct_secured": 30.4
      }
    },
    "july": {
      "enrolled": {
        "partners": 330,
        "leads": 1736,
        "installs": 800,
        "agg_eff": 46.1,
        "secured": 96,
        "pct_secured": 29.1
      },
      "eligible": {
        "partners": 62,
        "leads": 215,
        "installs": 64,
        "agg_eff": 29.8,
        "secured": 10,
        "pct_secured": 16.1
      },
      "nonmbg": {
        "partners": 173,
        "leads": 659,
        "installs": 206,
        "agg_eff": 31.3,
        "secured": 40,
        "pct_secured": 23.1
      }
    }
  }
};
