#!/usr/bin/env python
"""Refresh the MBG banner dashboard: re-run Metabase queries, regenerate data.js,
commit and push to GitHub Pages. Designed to run hourly via Windows Task Scheduler."""
import json, os, subprocess, urllib.request
from datetime import datetime, timezone, timedelta

REPO = os.path.dirname(os.path.abspath(__file__))
API_KEY = "mb_vgO9yv/ldumT74/svNNsIGyTU39WiNA32FMnEP8NSJQ="
URL = "https://metabase.wiom.in/api/dataset"
IST = timezone(timedelta(hours=5, minutes=30))


def run_sql(sql):
    payload = {"database": 113, "type": "native", "native": {"query": sql}}
    req = urllib.request.Request(
        URL, data=json.dumps(payload).encode(),
        headers={"x-api-key": API_KEY, "Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=300) as resp:
        data = json.loads(resp.read().decode())
    cols = [c["name"] for c in data["data"]["cols"]]
    rows = data["data"]["rows"]
    return [dict(zip(cols, r)) for r in rows]


def by_group(rows):
    return {r["GRP"]: r for r in rows}


def main():
    csp = by_group(run_sql(open(os.path.join(REPO, "query_csp_funnel.sql")).read()))
    conn = by_group(run_sql(open(os.path.join(REPO, "query_connection_funnel.sql")).read()))

    def g(d, k):
        return int(d.get(k) or 0)

    m, n = csp["MBG"], csp["Non-MBG"]
    cm, cn = conn["MBG"], conn["Non-MBG"]
    now = datetime.now(IST)

    data = {
        "last_updated": now.strftime("%d %b %Y, %I:%M %p IST"),
        "window_start": "09 Jul",
        "window_end": now.strftime("%d %b %Y"),
        "live": 425,
        "engagement": {
            "clicked": g(m, "CLICKERS"), "clicks": g(m, "TOTAL_CLICKS"),
            "c1": g(m, "C1"), "c2": g(m, "C2"), "c3": g(m, "C3"), "c4plus": g(m, "C4PLUS"),
        },
        "csp_funnel": {
            "mbg": {"clicked": g(m, "CLICKERS"), "slot": g(m, "REACHED_SLOT"),
                    "tech": g(m, "REACHED_TECH"), "install": g(m, "REACHED_INSTALL")},
            "non": {"clicked": g(n, "CLICKERS"), "slot": g(n, "REACHED_SLOT"),
                    "tech": g(n, "REACHED_TECH"), "install": g(n, "REACHED_INSTALL")},
        },
        "conn_funnel": {
            "mbg": {"connections": g(cm, "CONNECTIONS"), "slot_proposed": g(cm, "SLOT_PROPOSED"),
                    "slot_confirmed": g(cm, "SLOT_CONFIRMED"), "tech": g(cm, "TECH_ASSIGNED"),
                    "arrived": g(cm, "ARRIVED"), "installed": g(cm, "INSTALLED")},
            "non": {"connections": g(cn, "CONNECTIONS"), "slot_proposed": g(cn, "SLOT_PROPOSED"),
                    "slot_confirmed": g(cn, "SLOT_CONFIRMED"), "tech": g(cn, "TECH_ASSIGNED"),
                    "arrived": g(cn, "ARRIVED"), "installed": g(cn, "INSTALLED")},
        },
    }

    out = "// Auto-generated by refresh.py — do not edit by hand.\n"
    out += "window.DASHBOARD_DATA = " + json.dumps(data, indent=2) + ";\n"
    with open(os.path.join(REPO, "data.js"), "w", encoding="utf-8") as f:
        f.write(out)

    git = lambda *a: subprocess.run(["git", "-C", REPO, *a], check=True,
                                    capture_output=True, text=True)
    git("add", "data.js")
    status = subprocess.run(["git", "-C", REPO, "status", "--porcelain", "data.js"],
                            capture_output=True, text=True).stdout.strip()
    if not status:
        print(now.isoformat(), "no change")
        return
    git("-c", "user.name=Vikaswiom", "-c", "user.email=design.3@wiom.in",
        "commit", "-m", "chore: hourly data refresh " + data["last_updated"])
    git("push", "origin", "main")
    print(now.isoformat(), "pushed:", data["last_updated"])


if __name__ == "__main__":
    main()
