#!/usr/bin/env python
"""Refresh the MBG banner dashboard: re-run Metabase queries, regenerate data.js,
commit and push to GitHub Pages. Runs hourly via GitHub Actions (cloud cron);
can also be run locally / via Windows Task Scheduler."""
import json, os, subprocess, urllib.request
from datetime import datetime, timezone, timedelta

REPO = os.path.dirname(os.path.abspath(__file__))
URL = "https://metabase.wiom.in/api/dataset"
IST = timezone(timedelta(hours=5, minutes=30))


def get_api_key():
    """Read the Metabase key from env (GitHub secret) or a local .env fallback.
    Never hard-coded — this repo is public."""
    k = os.environ.get("METABASE_API_KEY")
    if k:
        return k.strip()
    for envf in (r"C:\credentials\.env", os.path.join(REPO, ".env")):
        if os.path.exists(envf):
            for line in open(envf, encoding="utf-8"):
                if line.strip().startswith("METABASE_API_KEY"):
                    return line.split("=", 1)[1].strip().strip('"').strip("'")
    raise RuntimeError("METABASE_API_KEY not set (env var or C:\\credentials\\.env)")


API_KEY = get_api_key()


def log(msg):
    line = datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S") + "  " + msg
    print(line)
    with open(os.path.join(REPO, "refresh.log"), "a", encoding="utf-8") as f:
        f.write(line + "\n")


def run_sql(sql):
    payload = {"database": 113, "type": "native", "native": {"query": sql}}
    req = urllib.request.Request(
        URL, data=json.dumps(payload).encode(),
        headers={"x-api-key": API_KEY, "Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=300) as resp:
        data = json.loads(resp.read().decode())
    cols = [c["name"] for c in data["data"]["cols"]]
    rows = data["data"]["rows"]
    return [dict(zip(cols, r)) for r in rows]


def by_group(rows):
    return {r["GRP"]: r for r in rows}


def main():
    log("start")
    csp = by_group(run_sql(open(os.path.join(REPO, "query_csp_funnel.sql")).read()))
    seg = {r["SEGMENT"]: r for r in run_sql(
        open(os.path.join(REPO, "query_segment_funnel.sql")).read())}
    tiers = {r["PERIOD"]: r for r in run_sql(
        open(os.path.join(REPO, "query_completion_tiers.sql")).read())}

    def g(d, k):
        return int(d.get(k) or 0)

    m = csp["MBG"]

    def seg_obj(key):
        s = seg[key]
        return {
            "base": g(s, "BASE_CSPS"), "active": g(s, "ACTIVE_CSPS"),
            # per-CSP: reached the stage at least once
            "slot": g(s, "SLOT_CSPS"), "tech": g(s, "TECH_CSPS"),
            "install": g(s, "INSTALL_CSPS"),
            # per-TASK: how many connections/tasks reached the stage
            "tasks": g(s, "CONNECTIONS"),
            "t_slot_prop": g(s, "T_SLOT_PROP"), "t_slot_conf": g(s, "T_SLOT_CONF"),
            "t_tech": g(s, "T_TECH"), "t_arrived": g(s, "T_ARRIVED"),
            "t_install": g(s, "T_INSTALL"),
        }

    now = datetime.now(IST)

    data = {
        "last_updated": now.strftime("%d %b %Y, %I:%M %p IST"),
        "window_start": "09 Jul",
        "window_end": now.strftime("%d %b %Y"),
        "live": 425,
        "engagement": {
            "clicked": g(m, "CLICKERS"), "clicks": g(m, "TOTAL_CLICKS"),
            "ct_profiles": g(m, "CT_PROFILES"),
            "c1": g(m, "C1"), "c2": g(m, "C2"), "c3": g(m, "C3"), "c4plus": g(m, "C4PLUS"),
        },
        "segments": {
            "clicked": seg_obj("A_clicked"),
            "noclick": seg_obj("B_noclick"),
            "nonmbg": seg_obj("C_nonmbg"),
        },
        "tiers": {p.lower(): {
            "csps": g(t, "CSPS"), "tasks": g(t, "TASKS"), "installs": g(t, "INSTALLS"),
            "overall_rate": float(t.get("OVERALL_RATE") or 0),
            "b": [g(t, "B0"), g(t, "B1"), g(t, "B2"), g(t, "B3"), g(t, "B4"), g(t, "B5")],
            "ge60": g(t, "GE60"),
        } for p, t in tiers.items()},
    }

    out = "// Auto-generated by refresh.py — do not edit by hand.\n"
    out += "window.DASHBOARD_DATA = " + json.dumps(data, indent=2) + ";\n"
    with open(os.path.join(REPO, "data.js"), "w", encoding="utf-8") as f:
        f.write(out)

    git = lambda *a: subprocess.run(["git", "-C", REPO, *a], check=True,
                                    capture_output=True, text=True)
    git("add", "data.js")
    status = subprocess.run(["git", "-C", REPO, "status", "--porcelain", "data.js"],
                            capture_output=True, text=True).stdout.strip()
    if not status:
        log("no change")
        return
    git("-c", "user.name=Vikaswiom", "-c", "user.email=design.3@wiom.in",
        "commit", "-m", "chore: hourly data refresh " + data["last_updated"])
    git("push", "origin", "HEAD:main")
    log("pushed: " + data["last_updated"])


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        log("ERROR: " + repr(exc))
        raise
